// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC41ubU8Sk3wYVBK95o5uuTZcobkg64wfM',
    appId: '1:247188164788:web:437f793426cea0acea87e1',
    messagingSenderId: '247188164788',
    projectId: 'realestate-a1c06',
    authDomain: 'realestate-a1c06.firebaseapp.com',
    storageBucket: 'realestate-a1c06.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC1cRh3l0GbaYFs58xsKZOn9zjiSRPqm0',
    appId: '1:247188164788:android:3da5a3bc036ed81dea87e1',
    messagingSenderId: '247188164788',
    projectId: 'realestate-a1c06',
    storageBucket: 'realestate-a1c06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzo-yGQeZkyCs60ih-E4z68WQAqeBb6Rw',
    appId: '1:247188164788:ios:00f0b8bd6595053aea87e1',
    messagingSenderId: '247188164788',
    projectId: 'realestate-a1c06',
    storageBucket: 'realestate-a1c06.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzo-yGQeZkyCs60ih-E4z68WQAqeBb6Rw',
    appId: '1:247188164788:ios:3efaf89c1e09acafea87e1',
    messagingSenderId: '247188164788',
    projectId: 'realestate-a1c06',
    storageBucket: 'realestate-a1c06.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
